#!/usr/bin/env bash
set -e

# Fail closed if required variables are missing
: "${POSTGRES_USER:?POSTGRES_USER is required}"
: "${FIREFLY_DB_USER:?FIREFLY_DB_USER is required}"
: "${FIREFLY_DB_PASSWORD:?FIREFLY_DB_PASSWORD is required}"
: "${FIREFLY_DB_NAME:=firefly}"
: "${PAPERLESS_DB_USER:?PAPERLESS_DB_USER is required}"
: "${PAPERLESS_DB_PASSWORD:?PAPERLESS_DB_PASSWORD is required}"
: "${PAPERLESS_DB_NAME:=paperless}"
: "${OPENPROJECT_DB_USER:?OPENPROJECT_DB_USER is required}"
: "${OPENPROJECT_DB_PASSWORD:?OPENPROJECT_DB_PASSWORD is required}"
: "${OPENPROJECT_DB_NAME:=openproject}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $FIREFLY_DB_USER WITH PASSWORD '$FIREFLY_DB_PASSWORD';
    CREATE DATABASE $FIREFLY_DB_NAME OWNER $FIREFLY_DB_USER;

    CREATE USER $PAPERLESS_DB_USER WITH PASSWORD '$PAPERLESS_DB_PASSWORD';
    CREATE DATABASE $PAPERLESS_DB_NAME OWNER $PAPERLESS_DB_USER;

    CREATE USER $OPENPROJECT_DB_USER WITH PASSWORD '$OPENPROJECT_DB_PASSWORD';
    CREATE DATABASE $OPENPROJECT_DB_NAME OWNER $OPENPROJECT_DB_USER;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -c "CREATE EXTENSION IF NOT EXISTS vector;"
