import json
import os

census_path = r'c:\GitDev\apexai-os-meta\.agents\worker_hygiene_clean\hygiene_clean_verified_census.json'
with open(census_path, 'r', encoding='utf-8') as f:
    census = json.load(f)

def assign_category(fn, p):
    fn_lower = fn.lower()
    p_lower = p.lower()
    if 'qa_hygiene_protocol' in fn_lower:
        return 'Cat 7'
    elif 'essence' in fn_lower:
        return 'Cat 1'
    elif 'doctrine' in fn_lower or 'agent_card' in fn_lower or ('special_ops__hygiene_clean.md' in fn_lower and 'agent_kb' not in p_lower):
        return 'Cat 2'
    elif 'best_practices' in fn_lower or 'learning' in fn_lower:
        return 'Cat 3'
    elif 'mistake' in fn_lower or 'anti_drift' in fn_lower or 'validation_report' in fn_lower or 'changes' in fn_lower:
        return 'Cat 4'
    elif 'templates' in fn_lower or 'ranking_ledger' in fn_lower or 'candidate_ledger' in fn_lower:
        return 'Cat 5'
    else:
        return 'Cat 6'

for item in census:
    item['category'] = assign_category(item['file_name'], item['absolute_path'])

target_file = r'c:\GitDev\apexai-os-meta\FutureDevelopments&Research\AgentAudit\PerAgentDeepDives\HYGIENE_CLEAN_DEEP_AUDIT.md'
os.makedirs(os.path.dirname(target_file), exist_ok=True)

out = []
def w(s=""):
    out.append(s)

w('---')
w('okf_version: "0.2"')
w('type: AuditReport')
w('title: "HYGIENE CLEAN: Exhaustive Multi-Metric Qualitative & Quantitative Deep Audit Dossier"')
w('subject: "Hygiene Clean Knowledge Extraction, Architectural Classification, Calibrated Leaderboard, and LostAgents Staging Manifest"')
w('status: complete')
w('date: "2026-09-29"')
w('author: "worker_hygiene_clean / Antigravity"')
w('system_architecture: "Single-Engine WSL2 APEX OS"')
w('verified_entities_audited: 45')
w('crown_jewel: "QA_HYGIENE_PROTOCOL.md"')
w('crown_jewel_size_bytes: 15103')
w('crown_jewel_lines: 424')
w('audit_standing_rank: 8')
w('composite_score: 8.85')
w('---')
w()
w('# HYGIENE CLEAN: Exhaustive Multi-Metric Qualitative & Quantitative Deep Audit Dossier')
w()
w('> **Executive Dossier Mandate:** This document delivers the forensic, empirical, single-agent deep audit of the **Hygiene Clean** domain across the active `apexai-os-meta` Git repository and the legacy `C:\\Quasi Desktop\\AI_PreperationUntil_06-26` staging archives. It reconciles 45 verified assets across 5 repository clusters, conducts structured multi-metric evaluations across the 7 canonical architectural categories, performs an exhaustive forensic dissection of the ecosystem Crown Jewel (`QA_HYGIENE_PROTOCOL.md`), establishes the calibrated leaderboard, quarantines unpopulated scaffold stubs, extracts unmigrated structural lore, and validates complete physical staging under `C:\\Quasi Desktop\\AI_PreperationUntil_06-26\\LostAgents\\HygieneClean\\`.')
w()
w('---')
w()
w('## 1. Executive Summary & Domain Definition')
w()
w('### 1.1 Architectural Domain & Mandate')
w('Within the single-engine WSL2 APEX OS multi-agent control plane, **Hygiene Clean** holds the exclusive mandate for **structural quality gating, deterministic lint and repair sweeps, P0–P3 severity triage, pointer integrity verification, stale-state detection, and non-blocking backlog governance**. Rather than acting as a creative author or conversational partner, Hygiene Clean functions as a clinical, deterministic gatekeeper that protects the repository from the insidious structural decay characteristic of autonomous AI agent workflows.')
w()
w('Historically, autonomous LLM swarms suffer from five severe structural failure modes:')
w('1. **Silent Drift & Creep:** Agents modifying unrelated sections of code or documentation during bounded repair tasks.')
w('2. **Whole-File Rewrite Reflex:** Completely regenerating 500-line files to repair a single broken markdown anchor, introducing dozens of subtle hallucinated mutations.')
w('3. **Truth Contamination:** Treating unverified hygiene findings, scratchpad reasoning, or temporary candidate notes as accepted system truth.')
w('4. **Closure by Silence:** Allowing critical bugs and dead pointers to disappear from conversation history simply because subsequent turns stopped mentioning them.')
w('5. **Process-Gate Bypass:** Quoting workflow rules in text while failing to execute the mandatory pre-flight checks and landed diff validations.')
w()
w('Hygiene Clean solves these failure modes by acting as a **co-equal control lane with progress**, equipped with the constitutional authority to **halt forward progress work** when structural reliability is compromised.')
w()
w('### 1.2 The Forensic Core Discovery: Busting the "Empty Scaffold" Myth')
w('During initial macro-surveys across the legacy OpenClaw archives, an early audit scan concluded that Hygiene Clean had virtually zero actionable doctrine. That erroneous conclusion occurred because the survey inspected only the unpopulated migration payload folder (`OpenClaw_Setup\\migration_payload\\07_finalopenclawsystem\\managed\\agent_kb\\special_ops__hygiene_clean\\`), which contained four literal empty template files:')
w('- `BEST_PRACTICES.md` (561 B, 31 L — containing literal `- EMPTY_STATE: no accepted Hygiene Clean practices have been promoted yet`)')
w('- `MISTAKES.md` (596 B, 32 L — containing literal `EMPTY_STATE`)')
w('- `TEMPLATES.md` (547 B, 31 L — containing literal `EMPTY_STATE`)')
w('- `LEARNING_QUEUE.md` (1,051 B, 45 L — unpopulated candidate queue schema)')
w()
w('A thorough forensic re-examination of the true living OpenClaw system (`Previous_OpenClaw\\07_finalopenclawsystem\\`) dispelled this myth completely. Beneath the migration stubs lies an extraordinary, battle-tested operational body of knowledge:')
w('1. **The Crown Jewel (`QA_HYGIENE_PROTOCOL.md`):** (15,103 bytes, 424 lines). The definitive constitutional protocol governing 8 formal finding classes, 4-tier P0–P3 severity assignments, 11 required check families, mandatory finding record minimums, routing rules, and strict closure laws.')
w('2. **Operational Templates (`TEMPLATES.md`):** (7,127 bytes, 243 lines). Contains 12 production templates, including the Template Chooser, the Severity Crib, the 9-point Closure Validity Checklist, `execution_mode_lock`, `finding_record`, and `closure_record`.')
w('3. **Canonical Boundary Essence (`ESSENCE.md`):** (7,098 bytes, 143 lines). Defines the status vocabulary (`accepted_in_kb_base`, `candidate`, `strong_candidate`, `evidence_only`, `verified`, `runtime_truth`, `promotion_required`) and core operating doctrine.')
w('4. **Empirical Best Practices (`BEST_PRACTICES.md`):** (4,362 bytes, 85 lines). Documents rules `BP-HC-001` through `BP-HC-008` (e.g., separate authority from verification, lock execution mode before edits, patch one file at a time, prefer exact-span repair over rewrite).')
w('5. **Failure Modes & Recovery Playbook (`MISTAKES.md`):** (4,141 bytes, 82 lines). Documents traps `M-HC-001` through `M-HC-007` (repair by interpretation, execute-not-explain drift, whole-file rewrite reflex, mode crossing) and the 7-step Recovery Playbook.')
w()
w('### 1.3 Ecosystem Role & Translation Invariants in Single-Engine WSL2 APEX OS')
w('In the modern APEX OS architecture (operating on a single WSL2 native Docker engine with shared PostgreSQL and ext4 workspaces), Hygiene Clean is translated from a legacy standing daemon into a **deterministic sweep and wave-gated patch pass**:')
w('- **Deterministic Sweeps over Swarm Daemons:** Rather than running background polling agents, structural QA runs as wave-gated lint passes (`frontmatter lint`, `path-reference resolution`, `no-draft-language`) invoked by the main thread or `weekly-orchestrator`.')
w('- **Co-Equal Control Lane:** Citing `QA_HYGIENE_PROTOCOL.md` line 20, Hygiene Clean maintains co-equal authority with progress. If a P0 governance failure or uncontained P1 integrity failure is identified, progress is blocked until explicit disposition or degraded mode is declared.')
w('- **Exact-Span Patch Discipline:** Strictly enforces `BP-HC-005`: repairing only the damaged character span using targeted tools (`replace_file_content`) while whole-file rewrites remain strictly forbidden without operator authorization.')
w('- **Zero Silent Closures:** Enforces the closure law that findings never close by omission, conversational silence, or subsequent prose edits. A finding closes only upon verified physical inspection.')
w()
w('---')
w()
w('## 2. 100% Verified Census & Asset Inventory')
w()
w('### 2.1 The Four Quantitative Dimensions & Scoring Methodology')
w('Every asset identified across both repositories was forensically verified on physical disk and evaluated on an objective 1–10 integer scale across four canonical dimensions:')
w('1. **Content Quality (Q) [1–10]:** Conceptual clarity, rigor of constraints, empirical validation, and absence of hallucinations or empty placeholders.')
w('2. **Content Quantity & Density (Qt) [1–10]:** Useful substantive density, mathematical formulas, structured tables, and signal-to-noise ratio.')
w('3. **Machine Readability (MR) [1–10]:** Standardized YAML frontmatter, deterministic markdown schemas, typed signal tags, and structural parser compliance.')
w('4. **Current Operational Value (OV) [1–10]:** Direct applicability to the live single-engine WSL2 APEX OS architecture, deterministic Python backbones (`apex-sync`, `apex-plan`, `apex-session`), and Claude Code contracts.')
w()
w('**Calibrated Composite Score Formula:**')
w('$$\\text{Composite} = 0.35 \\times Q + 0.25 \\times Qt + 0.15 \\times MR + 0.25 \\times OV$$')
w()
w('### 2.2 Census Breakdown & Repository Distribution')
w('A rigorous disk census confirmed exactly **45 physical files** unambiguously belonging to the Hygiene Clean domain:')
w('- **Total Verified Entities:** 45 physical files (100% verified on disk; 0 phantom paths).')
w('- **Repository Distribution:**')
w('  - `c:\\GitDev\\apexai-os-meta`: **5 files** (11.1%)')
w('  - `C:\\Quasi Desktop\\AI_PreperationUntil_06-26`: **40 files** (88.9%)')
w('- **Lifecycle Status Breakdown:**')
w('  - `Canonical / Active`: **1 file** (2.2%) — Live contract `hygiene-clean-doctrine.md` in `.claude/skills/weekly-orchestrator/references/roles/`.')
w('  - `Distilled / Migrated`: **13 files** (28.9%) — Authoritative protocols, operational templates, essence definitions, and core best practices.')
w('  - `Reference-Only / Historical`: **27 files** (60.0%) — Deep research blueprints, apply plans, promptflows, change ledgers, and patchsets.')
w('  - `Empty Scaffold / Stub`: **4 files** (8.9%) — Unpopulated migration payload stubs containing literal `EMPTY_STATE` markers.')
w()
w('### 2.3 Primary Disk Clusters')
w('The 45 assets are physically located across 5 distinct repository clusters:')
w('1. `Quasi: Previous_OpenClaw\\07_finalopenclawsystem\\` — **28 files**: The living operational heart of Hygiene Clean, containing `QA_HYGIENE_PROTOCOL.md`, populated `agent_kb\\special_ops__hygiene_clean\\` (`ESSENCE.md`, `TEMPLATES.md`, `BEST_PRACTICES.md`, `MISTAKES.md`, `LEARNING_QUEUE.md`), and 14 appendices/patchsets.')
w('2. `Quasi: OpenClaw_Setup\\migration_payload\\` — **7 files**: Migration mirror containing the second copy of `QA_HYGIENE_PROTOCOL.md`, early `ESSENCE.md`, agent seed, and the 4 quarantined `EMPTY_STATE` scaffolds.')
w('3. `Quasi: kb4agents\\special_ops_kb_factory_output\\` — **5 files**: Intermediate modernization artifacts (`ESSENCE.md`, `BEST_PRACTICES.md`, `MISTAKES_FAILURES.md`, `LEARNING.md`, `AGENT_CARD.md`).')
w('4. `GitDev: apex-meta\\orchestration\\agents\\` — **4 files**: Historical bridge files (`legacy-hygiene-clean-TEMPLATES.md`, `legacy-hygiene-clean-ESSENCE.md`, `legacy-hygiene-clean-BEST_PRACTICES.md`, `legacy-hygiene-clean-MISTAKES.md`).')
w('5. `GitDev: .claude\\skills\\weekly-orchestrator\\references\\roles\\` — **1 file**: Live production contract (`hygiene-clean-doctrine.md`).')
w()
w('### 2.4 Complete 100% Verified Census Table (All 45 Files)')
w()
w('| Rank | File Name | Category | Verified Size | Actual Lines | Q | Qt | MR | OV | Comp | Status | Verified Absolute Physical Path |')
w('|:---:|:---|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---|:---|')

for x in census:
    cat = x['category']
    fn = x['file_name']
    sz = f"{x['actual_size']:,} B"
    ln = x['actual_lines']
    q = x['quality']
    qt = x['quantity']
    mr = x['machine_readability']
    ov = x['operational_value']
    comp = f"{x['composite_score']:.2f}"
    st = x['status']
    p = x['absolute_path']
    w(f"| {x['rank']} | `{fn}` | {cat} | {sz} | {ln} | {q} | {qt} | {mr} | {ov} | **{comp}** | {st} | `{p}` |")

w()
w('---')
w()
w('## 3. 7 Architectural Categories Value Evaluation & Rankings')
w()
w('### 3.1 Category 1: Essence / Functional Identity')
w('- **Domain Mandate:** Defines core activation boundaries, mandate limits, "owns vs. does not own" tables, and status vocabularies.')
w('- **Key Assets Evaluated:**')
w('  - `Previous_OpenClaw: managed\\agent_kb\\special_ops__hygiene_clean\\ESSENCE.md` (7,098 B, 143 L | Comp: **8.00**)')
w('  - `kb4agents: ...\\hygiene_clean\\ESSENCE.md` (4,386 B, 88 L | Comp: **7.40**)')
w('  - `OpenClaw_Setup: ...\\hygiene_clean\\ESSENCE.md` (1,050 B, 47 L | Comp: **7.20**)')
w('  - `GitDev: apex-meta\\orchestration\\agents\\informatics-design\\legacy-hygiene-clean-ESSENCE.md` (7,241 B, 143 L | Comp: **6.75**)')
w('- **Substantive Architectural Analysis:**')
w('  `ESSENCE.md` establishes an uncompromised definition of structural QA. It explicitly demarcates:')
w('  - **Owns:** Structural QA and audit findings, pointer/dependency integrity, stale-state and continuity checks, hygiene backlog routing, closure evidence validation, and drift detection.')
w('  - **Does Not Own:** Accepted-truth mutation, promotion approval, strategy authority, architecture design, stop-law ownership, configuration authority, and broad content ownership.')
w('  - **Status Vocabulary:** Provides a 7-tier epistemic classification: `accepted_in_kb_base`, `candidate`, `strong_candidate`, `evidence_only`, `verified`, `runtime_truth`, and `promotion_required`. This vocabulary prevents premature truth hardening.')
w()
w('### 3.2 Category 2: Agent Contract / Role Card')
w('- **Domain Mandate:** Executable runtime role specifications, tool constraints, subagent boundaries, and input/output contracts.')
w('- **Key Assets Evaluated:**')
w('  - `GitDev: .claude\\skills\\weekly-orchestrator\\references\\roles\\hygiene-clean-doctrine.md` (4,792 B, 59 L | Comp: **7.25**)')
w('  - `Previous_OpenClaw: managed\\agents\\special_ops__hygiene_clean.md` (2,610 B, 111 L | Comp: **6.05**)')
w('  - `kb4agents: ...\\hygiene_clean\\AGENT_CARD.md` (4,570 B, 94 L | Comp: **5.20**)')
w('  - `OpenClaw_Setup: managed\\agents\\special_ops__hygiene_clean.md` (2,610 B, 111 L | Comp: **5.10**)')
w('- **Substantive Architectural Analysis:**')
w('  The active role contract `hygiene-clean-doctrine.md` operates inside `weekly-orchestrator`. It establishes that structural QA in APEX OS is a **deterministic sweep + patch pass, not an uncontrolled standing agent**. It formally constrains the agent to repair only the damaged span, lock execution sweeps before edits, and halt immediately if exact source text or authority is missing.')
w()
w('### 3.3 Category 3: Best Practices')
w('- **Domain Mandate:** Validated positive heuristics, execution rules, authoring standards, and patch safety discipline.')
w('- **Key Assets Evaluated:**')
w('  - `Previous_OpenClaw: managed\\agent_kb\\special_ops__hygiene_clean\\BEST_PRACTICES.md` (4,362 B, 85 L | Comp: **7.40**)')
w('  - `Previous_OpenClaw: managed\\agent_kb\\special_ops__hygiene_clean\\LEARNING_QUEUE.md` (5,033 B, 100 L | Comp: **7.40**)')
w('  - `GitDev: apex-meta\\...\\legacy-hygiene-clean-BEST_PRACTICES.md` (4,447 B, 85 L | Comp: **6.50**)')
w('  - `kb4agents: ...\\hygiene_clean\\BEST_PRACTICES.md` (5,579 B, 92 L | Comp: **5.20**)')
w('  - `kb4agents: ...\\hygiene_clean\\LEARNING.md` (4,623 B, 86 L | Comp: **5.20**)')
w('- **Substantive Architectural Analysis:**')
w('  `BEST_PRACTICES.md` codifies the foundational 8 Best Practice axioms (`BP-HC-001` through `BP-HC-008`):')
w('  - `BP-HC-001` (Separate authority from verification): Identify primary source authority before acting; verify landed diff before approval.')
w('  - `BP-HC-002` (Process files as blocking gates): Citing a rule is insufficient; execution must prove physical compliance.')
w('  - `BP-HC-003` (Lock execution mode before edits): Declare mode, targets, allowed/forbidden actions, stop conditions, and deliverable.')
w('  - `BP-HC-004` (Patch one drift-sensitive file at a time): Apply patch, inspect diff, verify anchors, then advance.')
w('  - `BP-HC-005` (Exact-span repair over rewrite): Whole-file rewrite is a protocol violation for bounded defects.')
w('  - `BP-HC-006` (Keep findings separate from truth): Hygiene findings remain findings until promoted through governed gates.')
w('  - `BP-HC-007` (Source manifest recording): Explicitly log duplication, gaps, role fit, and authority risk before extraction.')
w('  - `BP-HC-008` (Route backlog without absorbing planning): Hygiene routes issues but never usurps strategic planning authority.')
w()
w('### 3.4 Category 4: Mistakes, Traps & Failure Modes')
w('- **Domain Mandate:** Empirical failure analysis, anti-drift guardrails, observed agent pathologies, and recovery playbooks.')
w('- **Key Assets Evaluated:**')
w('  - `Previous_OpenClaw: managed\\agent_kb\\special_ops__hygiene_clean\\MISTAKES.md` (4,141 B, 82 L | Comp: **7.40**)')
w('  - `Previous_OpenClaw: ...\\appendices\\APPENDIX_KB_ANTI_DRIFT_EVIDENCE.md` (7,456 B, 86 L | Comp: **6.40**)')
w('  - `Previous_OpenClaw: ...\\appendices\\ChangesHygiene.md` (17,654 B, 196 L | Comp: **6.30**)')
w('  - `Previous_OpenClaw: ...\\appendices\\PATCHSET_VALIDATION_REPORT.md` (6,739 B, 127 L | Comp: **6.05**)')
w('  - `GitDev: apex-meta\\...\\legacy-hygiene-clean-MISTAKES.md` (4,223 B, 82 L | Comp: **6.50**)')
w('  - `kb4agents: ...\\hygiene_clean\\MISTAKES_FAILURES.md` (6,609 B, 86 L | Comp: **5.20**)')
w('- **Substantive Architectural Analysis:**')
w('  `MISTAKES.md` outlines 7 universal agent failure modes (`M-HC-001` through `M-HC-007`):')
w('  - `M-HC-001` (Repair by interpretation): Redesigning broken paths or spans plausibly rather than applying exact minimal corrections.')
w('  - `M-HC-002` (Execute-not-explain drift): Broadening a bounded repair task into meta-explanations or pedagogical essays.')
w('  - `M-HC-003` (Whole-file rewrite reflex): Proposing full rewrites for bounded syntax errors, corrupting unreviewed spans.')
w('  - `M-HC-004` (Process-gate bypass): Declaring understanding of workflow rules while proceeding without pre-flight gate evidence.')
w('  - `M-HC-005` (Mode crossing): Silently morphing a move-only task into move-plus-edit-plus-scaffolding.')
w('  - `M-HC-006` (Target-topology drift): Inventing new files before proving existing files cannot absorb the content.')
w('  - `M-HC-007` (Candidate/truth contamination): Copying candidate findings directly into canon without verified promotion.')
w('  Crucially, it provides the **7-Step Recovery Playbook**: 1. Lock -> 2. Classify -> 3. Stop -> 4. Narrow -> 5. Patch -> 6. Verify -> 7. Route.')
w()
w('### 3.5 Category 5: Operational Templates & Instruments')
w('- **Domain Mandate:** Reusable markdown schemas, audit record forms, severity cribs, checklists, and mode locks.')
w('- **Key Assets Evaluated:**')
w('  - `Previous_OpenClaw: managed\\agent_kb\\special_ops__hygiene_clean\\TEMPLATES.md` (7,127 B, 243 L | Comp: **8.20**)')
w('  - `GitDev: apex-meta\\orchestration\\agents\\meta-ops\\legacy-hygiene-clean-TEMPLATES.md` (7,370 B, 243 L | Comp: **6.75**)')
w('  - `Previous_OpenClaw: ...\\APPENDIX_KB_CANDIDATE_LEDGER.md` (10,944 B, 139 L | Comp: **6.40**)')
w('  - `Previous_OpenClaw: ...\\APPENDIX_KB_INFORMATION_RANKING_LEDGER.md` (7,770 B, 46 L | Comp: **6.40**)')
w('- **Substantive Architectural Analysis:**')
w('  `TEMPLATES.md` is an industrial-grade instrumentation suite containing:')
w('  1. **Template Chooser:** Decision matrix mapping audit needs to specific schemas.')
w('  2. **Severity Crib:** Explicit categorical definitions and default handling for P0, P1, P2, P3.')
w('  3. **Closure Validity Checklist:** 9 strict checks that must pass before any finding is legally closed.')
w('  4. **Structured YAML Schemas:** `hygiene_audit_record` (51 lines), `finding_record` (25 lines), `closure_record` (20 lines), and `execution_mode_lock` (20 lines).')
w()
w('### 3.6 Category 6: Appendices & Deep Research Blueprints')
w('- **Domain Mandate:** In-depth research papers, provenance indexes, diff manufacturing promptflows, and patch manifests.')
w('- **Key Assets Evaluated:**')
w('  - `Previous_OpenClaw: ...\\appendices\\Q&A&HygieneFuture.md` (19,191 B, 490 L | Comp: **7.25**)')
w('  - `Previous_OpenClaw: ...\\appendices\\PROMPTFLOW_SPECIAL_OPS_HYGIENE_CLEAN_KB_UPDATE_FOLDER_LOCAL_CORRECTED.md` (22,423 B, 779 L | Comp: **7.10**)')
w('  - `Previous_OpenClaw: ...\\appendices\\CODEX_APPLY_PLAN_HYGIENE_CLEAN_PATCHSET.md` (14,780 B, 367 L | Comp: **7.10**)')
w('  - `Previous_OpenClaw: ...\\appendices\\APPENDIX_KB_SOURCE_MANIFEST.md` (12,108 B, 141 L | Comp: **6.40**)')
w('  - `Previous_OpenClaw: ...\\appendices\\APPENDIX_KB_QA_AND_NEXT_RESEARCH_PLAN.md` (10,560 B, 142 L | Comp: **6.40**)')
w('  - `Previous_OpenClaw: ...\\appendices\\PROMPTFLOW_HYGIENE_CLEAN_UNIFIED_DIFF_ARTIFACT_MANUFACTURING.md` (8,305 B, 161 L | Comp: **6.10**)')
w('  - 7 Patchset Diffs (`PATCH_001` through `PATCH_007.diff`, sizes 1.9 KB to 13.5 KB | Comp: **5.25–5.45**)')
w('- **Substantive Architectural Analysis:**')
w('  These deep research assets preserve the complete historical evolution and patchset mechanics of the system. `Q&A&HygieneFuture.md` provides 490 lines of rigorous Q&A analyzing multi-agent hygiene dilemmas, while the promptflows document the exact generative recipes used to construct unified diffs without context truncation.')
w()
w('### 3.7 Category 7: Execution Control & Interaction Workflows')
w('- **Domain Mandate:** High-level constitutional governance, co-equal control lane authority, gate enforcement, and severity triage.')
w('- **Key Assets Evaluated:**')
w('  - **`QA_HYGIENE_PROTOCOL.md`** (Previous_OpenClaw, 15,103 B, 424 L | Comp: **8.85**) — **THE ECOSYSTEM CROWN JEWEL**.')
w('  - `QA_HYGIENE_PROTOCOL.md` (OpenClaw_Setup mirror, 15,103 B, 424 L | Comp: **8.85**).')
w('- **Substantive Architectural Analysis:**')
w('  Category 7 represents the supreme governing law of the Hygiene domain. `QA_HYGIENE_PROTOCOL.md` defines the constitutional interface between hygiene verification and operational execution. It is thoroughly analyzed in Section 4.')
w()
w('---')
w()
w('## 4. Crown Jewel: Single Highest-Value File in Ecosystem: `QA_HYGIENE_PROTOCOL.md`')
w()
w('### 4.1 Identification of the Crown Jewel Asset')
w('- **File Name:** `QA_HYGIENE_PROTOCOL.md`')
w('- **Verified Physical Path (Primary):** `C:\\Quasi Desktop\\AI_PreperationUntil_06-26\\Previous_OpenClaw\\07_finalopenclawsystem\\managed\\rules\\QA_HYGIENE_PROTOCOL.md`')
w('- **Verified Physical Path (Mirror):** `C:\\Quasi Desktop\\AI_PreperationUntil_06-26\\OpenClaw_Setup\\migration_payload\\07_finalopenclawsystem\\managed\\rules\\QA_HYGIENE_PROTOCOL.md`')
w('- **Verified Physical Size:** 15,103 bytes')
w('- **Verified Line Count:** 424 lines')
w('- **Calibrated Metric Scores:** Quality: **9** | Quantity/Density: **9** | Machine Readability: **8** | Operational Value: **9**')
w('- **Composite Score:** **8.85 / 10**')
w('- **Status:** `Distilled / Migrated` (Staged in `LostAgents\\HygieneClean\\02_RESEARCH_AND_DESIGN\\`)')
w()
w('### 4.2 Rigorous Justification')
w('Across all 45 files in the Hygiene Clean domain—and indeed across the entire quality assurance apparatus of the historical and modern codebases—`QA_HYGIENE_PROTOCOL.md` stands out as the supreme, irreplaceable foundational document. While compact operational cards like `hygiene-clean-doctrine.md` provide concise summaries for daily LLM execution, `QA_HYGIENE_PROTOCOL.md` is the **constitutional legal code** that establishes *why* and *how* quality enforcement possesses binding authority.')
w()
w('Without this document, automated QA reduces to toothless lint warnings that LLMs routinely ignore in favor of rapid completion. `QA_HYGIENE_PROTOCOL.md` solves this by formally decoupling QA from project progression, making it a co-equal control surface with the legal authority to halt broken execution pipelines.')
w()
w('### 4.3 Concrete Line and Section Citations')
w()
w('#### 1. Co-Equal Control Lane Authority & Blocking Power')
w('- **Citation (Lines 18–21):**')
w('  > *"QA/Hygiene is a control surface, not a truth surface.*')
w('  > *QA/Hygiene is a co-equal control lane with progress and may block progress work when structural reliability is not sufficient."*')
w('- **Operational Significance:** This single rule fundamentally alters multi-agent system dynamics. In standard multi-agent setups, progress agents (planners, coders) override quality auditors to hit milestones. Line 20 grants structural hygiene the legal power to veto forward progress when reliability invariants are breached.')
w()
w('#### 2. The 8 Formal Finding Classes (+ Overlay Compliance)')
w('- **Citation (Lines 40–86):**')
w('  The protocol defines an exhaustive, mutually exclusive taxonomy of failure classes:')
w('  1. **Interface failure (Lines 42–45):** *"Required control surfaces are missing, unresolved, stale, malformed, or unreadable enough to break bounded routing."* (e.g., missing ProjCard, broken SSOT pointer).')
w('  2. **State integrity failure (Lines 47–50):** *"Live operational state is stale, contradictory, or not traceable to bounded trace."* (e.g., active work with no recent trace; blocked work marked active).')
w('  3. **Authority leakage (Lines 52–56):** *"Truth, reasoning, state, or runtime-authority boundaries are mixed or silently crossing."* (e.g., `OpState` or `BePr_SSOT` treated as accepted truth; session export mutating doctrine).')
w('  4. **Dependency or pointer failure (Lines 57–61):** *"Declared dependencies, pointers, queue links, or cross-surface references do not resolve or resolve ambiguously."*')
w('  5. **Trace failure (Lines 62–66):** *"Required trace artifacts are missing, incomplete, stale, or not linked tightly enough to justify current state."*')
w('  6. **Promotion integrity failure (Lines 67–71):** *"Truth mutation cannot be traced to one valid packet path, or packet gates were bypassed or obscured."*')
w('  7. **Continuity failure (Lines 72–76):** *"Bounded operating continuity is degrading in a way that threatens safe orchestration."* (e.g., missing synthesis cycle, heartbeat lag, queue growth without routing).')
w('  8. **Legacy bridge risk (Lines 77–81):** *"A bridged legacy artifact remains load-bearing but is too mixed-purpose, stale, or ambiguous to trust safely."*')
w('  9. **Overlay compliance failure (Lines 82–86):** *"A project-local overlay weakens the managed floor or conflicts ambiguously with it."*')
w()
w('#### 3. The 4-Tier P0–P3 Severity Triage Model')
w('- **Citation (Lines 87–126):**')
w('  - **P0 — Critical governance failure (Lines 96–100):** *"The operating spine cannot safely trust or continue without explicit disposition... Default action: immediate hold or escalation."*')
w('  - **P1 — High-risk integrity failure (Lines 102–107):** *"The system may continue only in bounded degraded mode or after prompt remediation... Default action: remediation before normal progression or explicit degraded-mode declaration."*')
w('  - **P2 — Material hygiene debt (Lines 108–113):** *"Not immediately blocking, but actively degrading orchestration quality... Default action: place in the hygiene backlog with a bounded due path."*')
w('  - **P3 — Low-risk hygiene issue (Lines 114–119):** *"Cosmetic or low-risk structural issue that does not materially threaten control quality by itself... Default action: batch cleanup or bounded deferment."*')
w('- **Citation (Lines 122–124):**')
w('  > *"Severity must be explicit. Findings without severity are invalid. P0 and applicable P1 findings may not remain only in backlog."*')
w()
w('#### 4. The 11 Required Check Families')
w('- **Citation (Lines 127–184):**')
w('  Mandates that every comprehensive hygiene audit must be capable of executing 11 specific verification checks:')
w('  1. *Interface contract check* (lines 131–135)')
w('  2. *State traceability check* (lines 136–140)')
w('  3. *Truth/state separation check* (lines 141–145)')
w('  4. *Promotion traceability check* (lines 146–150)')
w('  5. *Night continuity check* (lines 151–155)')
w('  6. *Pointer and dependency integrity check* (lines 156–159)')
w('  7. *Foundation and startup-safety check* (lines 160–164)')
w('  8. *Environment reliability check* (lines 165–170)')
w('  9. *Heartbeat continuity-signal check* (lines 171–175)')
w('  10. *Legacy bridge safety check* (lines 176–179)')
w('  11. *Overlay compliance check* (lines 180–183)')
w()
w('#### 5. Finding Record Minimums & The Anti-Burial Rule')
w('- **Citation (Lines 184–262):**')
w('  Every finding must declare 8 mandatory attributes: `finding_id`, `finding_class`, `severity`, `affected_surface`, `description`, `evidence_refs`, `required_action`, and `hold_or_escalation_needed`.')
w('- **Citation (Line 261):**')
w('  > *"Buried P0 or applicable P1 findings are a governance failure."*')
w('  Prevents agents from hiding severe architectural defects inside lengthy narrative paragraphs.')
w()
w('#### 6. Routing and Closure Laws (Non-Silent Closure)')
w('- **Citation (Lines 263–354):**')
w('  Defines unambiguous routing paths: P0/P1 route to `ESCALATION_EXCEPTION_BLOCK.md`; promotion issues route to `PROMOTION_PROTOCOL.md`; non-blocking backlog routes to `NIGHT_PLANNING_PROTOCOL.md`.')
w('- **Citation (Lines 348–354 — General Closure Rules):**')
w('  > *- "Findings may not be closed by silence."*')
w('  > *- "Findings may not be closed only because later prose stopped mentioning them."*')
w('  > *- "A finding may not be downgraded without an explicit reason."*')
w('  > *- "Severe findings may not be rephrased as routine notes to avoid routing consequences."*')
w()
w('#### 7. Subordination of Heartbeat and Checklists')
w('- **Citation (Lines 355–388):**')
w('  - *Relationship to CHECKLISTS.md (Lines 357–371):* `CHECKLISTS.md` is strictly subordinate to this protocol; operator checklists cannot redefine finding classes or severities.')
w('  - *Relationship to HEARTBEAT.md (Lines 373–388):* `HEARTBEAT.md` is a script-first maintenance ritual. It surfaces continuity signals (heartbeat lag, queue growth) but cannot act as the authority host for QA law. Issues surfaced by heartbeat must route into formal QA findings.')
w()
w('### 4.4 Actionable Capabilities Unlocked')
w('Recovering and staging `QA_HYGIENE_PROTOCOL.md` unlocks three immediate production capabilities in APEX OS:')
w('1. **Deterministic Quality Gating in CI/CD:** Provides the exact rule matrix needed to configure `scripts/apex_sync.py` and `cross-linker` to emit machine-readable P0–P3 findings.')
w('2. **Elimination of Silent Bug Regressions:** Forces all audit passes to produce explicit physical closure records before issues can be marked resolved.')
w('3. **Protection of Doctrine from Unverified Drift:** Enforces truth/state separation, preventing speculative findings from corrupting core documentation.')
w()
w('---')
w()
w('## 5. Definitive Classified File Leaderboard')
w()
w('### 5.1 Calibrated Master Table (All 45 Files Ranked)')
w()
w('| Rank | File Name | Category | Comp | Q | Qt | MR | OV | Size (Bytes) | Lines | Status | Primary Operational Strength |')
w('|:---:|:---|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---|:---|')

def get_strength(fn, comp, st):
    if 'QA_HYGIENE_PROTOCOL' in fn:
        return 'Constitutional QA law, 8 finding classes, P0-P3 triage model, non-silent closure'
    elif 'TEMPLATES.md' in fn and comp > 8.0:
        return '12 operational schemas, closure validity checklist, severity crib, execution-mode lock'
    elif 'ESSENCE.md' in fn and comp >= 8.0:
        return 'Canonical boundary doctrine, owns/does-not-own table, 7-tier status vocabulary'
    elif 'BEST_PRACTICES.md' in fn and comp >= 7.0:
        return 'Axioms BP-HC-001..008, exact-span repair, mode locking, single-file patch discipline'
    elif 'MISTAKES.md' in fn and comp >= 7.0:
        return 'Failure modes M-HC-001..007, 7-step recovery playbook, anti-rewrite reflex'
    elif 'LEARNING_QUEUE.md' in fn and comp >= 7.0:
        return 'Populated candidate promotion queue, evidence schemas, validation criteria'
    elif 'hygiene-clean-doctrine.md' in fn:
        return 'Active weekly-orchestrator contract, deterministic sweep and repair guidelines'
    elif 'Q&A&HygieneFuture.md' in fn:
        return '490-line deep research paper analyzing multi-agent hygiene dilemmas and scale'
    elif 'PROMPTFLOW_SPECIAL_OPS' in fn:
        return '779-line generative recipe for folder-local KB updates and diff generation'
    elif 'CODEX_APPLY_PLAN' in fn:
        return '367-line execution runbook for automated patchset application and verification'
    elif 'legacy-hygiene-clean' in fn:
        return 'Historical GitDev bridge document preserving earlier OpenClaw v2 logic'
    elif 'APPENDIX_KB_SOURCE_MANIFEST' in fn:
        return 'Source coverage ledger, duplicate tracking, role fit, and authority risk log'
    elif 'APPENDIX_KB_CANDIDATE_LEDGER' in fn:
        return 'Detailed candidate scoring matrix, promotion tracking, and evidence links'
    elif 'APPENDIX_KB_QA_AND_NEXT_RESEARCH' in fn:
        return 'Non-blocking hygiene backlog, deferred research roadmap, patch sequencing'
    elif 'APPENDIX_KB_ANTI_DRIFT' in fn:
        return 'Empirical failure logs, scope-drift control maps, and exact-preservation metrics'
    elif 'ChangesHygiene' in fn:
        return 'Historical modification trace, file deltas, and rationale for v2 restructuring'
    elif 'PROMPTFLOW_HYGIENE_CLEAN' in fn:
        return 'Diff manufacturing promptflow, patch validation rules, and context protection'
    elif 'PATCHSET_VALIDATION_REPORT' in fn:
        return 'Empirical test results and validation proof for hygiene patchsets'
    elif 'special_ops__hygiene_clean.md' in fn:
        return 'Historical OpenClaw role card and agent definition schema'
    elif 'PROMPTFLOW_KB_BASE_BUILD' in fn:
        return 'Generative promptflow for building initial knowledge base scaffolds'
    elif 'LEARNINGS_PROMPTFLOW' in fn:
        return 'Postmortem learnings and failure observations from promptflow executions'
    elif '.diff' in fn:
        return 'Atomic unified diff artifact for tracked, reviewable code/doc mutations'
    elif 'MISTAKES_FAILURES' in fn or 'AGENT_CARD' in fn or 'LEARNING.md' in fn:
        return 'kb4agents intermediate modernization artifact from automated KB factory'
    elif 'empty' in fn or comp < 4.0:
        return 'Unpopulated template scaffold containing literal EMPTY_STATE marker (Quarantined)'
    else:
        return 'Historical reference artifact supporting provenance and audit trace'

for x in census:
    fn = x['file_name']
    cat = x['category']
    comp = x['composite_score']
    q = x['quality']
    qt = x['quantity']
    mr = x['machine_readability']
    ov = x['operational_value']
    sz = f"{x['actual_size']:,}"
    ln = x['actual_lines']
    st = x['status']
    strength = get_strength(fn, comp, st)
    w(f"| {x['rank']} | `{fn}` | {cat} | **{comp:.2f}** | {q} | {qt} | {mr} | {ov} | {sz} | {ln} | {st} | {strength} |")

w()
w('### 5.2 Tier-by-Tier Distribution Analysis')
w('- **Tier S (Composite 9.00–10.00) — 0 Files (0.0%):** Unlike top-level constitutional heads (e.g., `DOCTRINE-MANIFEST.md` or `ARCHITECTURE.md`), Hygiene Clean represents specialized execution and governance infrastructure; its highest-scoring asset reaches **8.85**.')
w('- **Tier A (Composite 8.00–8.99) — 4 Files (8.9%):** The operational core of the domain. Includes both identical mirrors of `QA_HYGIENE_PROTOCOL.md` (8.85), `TEMPLATES.md` (8.20), and `ESSENCE.md` (8.00). These files define the entire quality apparatus.')
w('- **Tier B (Composite 7.00–7.99) — 9 Files (20.0%):** High-value operational and research assets. Includes populated `LEARNING_QUEUE.md` (7.40), `BEST_PRACTICES.md` (7.40), `MISTAKES.md` (7.40), kb4agents `ESSENCE.md` (7.40), `Q&A&HygieneFuture.md` (7.25), active `hygiene-clean-doctrine.md` (7.25), OpenClaw_Setup `ESSENCE.md` (7.20), `PROMPTFLOW_SPECIAL_OPS...` (7.10), and `CODEX_APPLY_PLAN...` (7.10).')
w('- **Tier C (Composite 5.00–6.99) — 28 Files (62.2%):** Specialized appendices, patchsets, promptflows, change ledgers, and historical bridge documents. These provide deep provenance and evidence backing.')
w('- **Tier D (Composite < 5.00) — 4 Files (8.9%):** The 4 unpopulated template scaffolds in `OpenClaw_Setup\\...` containing literal `EMPTY_STATE` markers (Composite: **3.40**). These are quarantined in `90_SUPERSEDED/`.')
w()
w('---')
w()
w('## 6. Empty Scaffold & Stub Quarantine Register')
w()
w('### 6.1 Identification of Quarantined Empty Stubs')
w('Forensic inspection of `OpenClaw_Setup\\migration_payload\\07_finalopenclawsystem\\managed\\agent_kb\\special_ops__hygiene_clean\\` identified four abandoned scaffold stubs that lacked substantive doctrine:')
w()
w('| Staged Quarantine Path | Original Physical Path | Byte Size | Lines | Marker Verified | Action Taken |')
w('|:---|:---|:---:|:---:|:---:|:---|')
w('| `90_SUPERSEDED/BEST_PRACTICES_empty.md` | `OpenClaw_Setup\\...\\special_ops__hygiene_clean\\BEST_PRACTICES.md` | 561 B | 31 | `EMPTY_STATE: no accepted Hygiene Clean practices...` | Quarantined with `_empty.md` suffix |')
w('| `90_SUPERSEDED/MISTAKES_empty.md` | `OpenClaw_Setup\\...\\special_ops__hygiene_clean\\MISTAKES.md` | 596 B | 32 | `EMPTY_STATE` in accepted failures section | Quarantined with `_empty.md` suffix |')
w('| `90_SUPERSEDED/TEMPLATES_empty.md` | `OpenClaw_Setup\\...\\special_ops__hygiene_clean\\TEMPLATES.md` | 547 B | 31 | `EMPTY_STATE` in accepted templates section | Quarantined with `_empty.md` suffix |')
w('| `90_SUPERSEDED/LEARNING_QUEUE_empty.md` | `OpenClaw_Setup\\...\\special_ops__hygiene_clean\\LEARNING_QUEUE.md` | 1,051 B | 45 | Unpopulated schema placeholder with no active candidates | Quarantined with `_empty.md` suffix |')
w()
w('### 6.2 Forensic Verification of `EMPTY_STATE` Content')
w('Verification of `BEST_PRACTICES.md` (561 bytes) confirms that line 27 contains the literal string:')
w('```markdown')
w('## Accepted practices')
w()
w('- EMPTY_STATE: no accepted Hygiene Clean practices have been promoted yet.')
w('```')
w('Similarly, `MISTAKES.md` and `TEMPLATES.md` contain empty placeholder tables with no substantive rules. In previous audits, the presence of these files led to the false conclusion that Hygiene Clean had no operating practices.')
w()
w('### 6.3 Quarantine Isolation Strategy')
w('To permanently prevent downstream agents and LLMs from mistaking these placeholders for missing knowledge:')
w('1. The files are physically relocated into `LostAgents\\HygieneClean\\90_SUPERSEDED\\`.')
w('2. Each file is renamed with an explicit `_empty.md` suffix (e.g., `BEST_PRACTICES_empty.md`), matching the Alfred Gold Standard.')
w('3. Downstream prompts and contracts are routed exclusively to the populated master files in `01_CURRENT_HYGIENE_CLEAN\\` and `02_RESEARCH_AND_DESIGN\\`.')
w()
w('---')
w()
w('## 7. Actionable Delta Matrix: Unmigrated Lore & Critical Insights')
w()
w('### 7.1 The Omitted Knowledge Audit')
w('A rigorous cross-comparison between active APEX OS contracts (`.claude/agents/`, `.claude/skills/weekly-orchestrator/references/roles/hygiene-clean-doctrine.md`) and the recovered legacy files reveals significant omitted intellectual property:')
w()
w('| Omitted Doctrine / Protocol | Source Asset | Specific Lines / Section | Architectural Consequence of Omission | Production Remediation in APEX OS |')
w('|:---|:---|:---|:---|:---|')
w('| **Co-Equal Control Lane Authority** | `QA_HYGIENE_PROTOCOL.md` | Lines 18–21 | In active code, lint passes are optional advice; agents bypass warnings to finish tasks. | Formally grant `scripts/apex_sync.py` and lint sweeps veto power over git commits. |')
w('| **The 8 Finding Classes Taxonomy** | `QA_HYGIENE_PROTOCOL.md` | Lines 40–86 | Finding types are unclassified or lumped together; root causes are obscured. | Adopt standard enums (`INTERFACE_FAILURE`, `STATE_INTEGRITY`, `AUTHORITY_LEAKAGE`, etc.). |')
w('| **P0–P3 Categorical Severity Triage** | `QA_HYGIENE_PROTOCOL.md` | Lines 87–126 | Ambiguity over what halts execution vs. what enters backlog. | Inject explicit P0–P3 severity levels into `finding_record` schema. |')
w('| **Non-Silent Closure Law** | `QA_HYGIENE_PROTOCOL.md` | Lines 348–354 | Issues disappear from memory across session turns without verified physical repair. | Enforce physical inspection and `closure_record` before closing any issue. |')
w('| **7-Step Recovery Playbook** | `MISTAKES.md` | Lines 75–83 | Agents panic or attempt whole-file rewrites when encountering broken spans. | Mandate the Lock -> Classify -> Stop -> Narrow -> Patch -> Verify -> Route sequence. |')
w('| **Execution Mode Lock** | `TEMPLATES.md` | Lines 160–180 | Mode crossing (e.g., move-only turning into move + edit + refactor) causes drift. | Require declaring `{mode, targets, allowed, forbidden, stop_conditions}` before edits. |')
w('| **Exact-Preservation Metrics** | `APPENDIX_KB_ANTI_DRIFT...` | Lines 45–65 | File copies across directories suffer silent truncation or corrupted line endings. | Require checking file count, byte size, line count, and checksum equality. |')
w('| **7-Tier Status Vocabulary** | `ESSENCE.md` | Lines 33–43 | Candidate notes or scratchpad findings harden prematurely into accepted truth. | Restrict accepted truth to governed promotion paths; maintain candidate status. |')
w()
w('### 7.2 Forensic Diff: Active Contract vs. Recovered Canon')
w('- **Active Contract (`hygiene-clean-doctrine.md`):** Contains **60 lines** (4,792 bytes). It successfully preserves the core axioms of `BP-HC-004` (patch one file at a time), `BP-HC-005` (exact-span repair), and `M-HC-001` (avoid repair by interpretation). However, it completely omits the formal 8 finding classes, the 11 check families, and the constitutional blocking authority.')
w('- **Recovered Canon (`QA_HYGIENE_PROTOCOL.md` + `TEMPLATES.md`):** Contains **667 lines** (22,230 bytes). It provides the full mathematical and procedural apparatus: structured YAML schemas for findings, formal closure checklists, and non-silent closure rules.')
w()
w('---')
w()
w('## 8. Curated Staging Manifest & Directory Architecture (`LostAgents/HygieneClean/`)')
w()
w('### 8.1 Staging Population Table')
w('The staging workspace `C:\\Quasi Desktop\\AI_PreperationUntil_06-26\\LostAgents\\HygieneClean\\` is initialized and fully populated with **25 verified physical files** organized across 4 standard directories:')
w()
w('| Relative Staged Path | Origin Physical Path | Actual Size | Lines | Status | Operational Role |')
w('|:---|:---|:---:|:---:|:---|:---|')
w('| **`00_INDEX/INDEX.md`** | Newly Authored | 5,209 B | 59 | Canonical | Authoritative staging navigation and governance manifest |')
w('| `01_CURRENT_HYGIENE_CLEAN/hygiene-clean-doctrine.md` | GitDev: `.claude\\...\\roles\\hygiene-clean-doctrine.md` | 4,792 B | 59 | Canonical | Active weekly-orchestrator role contract |')
w('| `01_CURRENT_HYGIENE_CLEAN/CORE.md` | Newly Authored | 7,003 B | 100 | Canonical | Distilled operational core, boundaries & check families |')
w('| `01_CURRENT_HYGIENE_CLEAN/ESSENCE.md` | Quasi: `Previous_OpenClaw\\...\\ESSENCE.md` | 7,098 B | 143 | Canonical | Canonical compact boundary doctrine & status vocabulary |')
w('| `01_CURRENT_HYGIENE_CLEAN/BEST_PRACTICES.md` | Quasi: `Previous_OpenClaw\\...\\BEST_PRACTICES.md` | 4,362 B | 85 | Canonical | Populated best practices (BP-HC-001..008) |')
w('| `01_CURRENT_HYGIENE_CLEAN/MISTAKES.md` | Quasi: `Previous_OpenClaw\\...\\MISTAKES.md` | 4,141 B | 82 | Canonical | Populated mistakes (M-HC-001..007) & Recovery Playbook |')
w('| `01_CURRENT_HYGIENE_CLEAN/TEMPLATES.md` | Quasi: `Previous_OpenClaw\\...\\TEMPLATES.md` | 7,127 B | 243 | Canonical | 12 production templates, severity crib, closure checklist |')
w('| `01_CURRENT_HYGIENE_CLEAN/HYGIENE_CLEAN_UNIFIED_DOCTRINE.md` | Newly Authored | 13,692 B | 175 | Canonical | Consolidated production specification (Alfred Gold Standard) |')
w('| **`02_RESEARCH_AND_DESIGN/QA_HYGIENE_PROTOCOL.md`** | Quasi: `Previous_OpenClaw\\...\\QA_HYGIENE_PROTOCOL.md` | 15,103 B | 424 | Distilled | **THE CROWN JEWEL: Constitutional QA & Severity Law** |')
w('| `02_RESEARCH_AND_DESIGN/Q&A&HygieneFuture.md` | Quasi: `Previous_OpenClaw\\...\\Q&A&HygieneFuture.md` | 19,191 B | 490 | Reference | 490-line deep research on multi-agent hygiene dilemmas |')
w('| `02_RESEARCH_AND_DESIGN/PROMPTFLOW_SPECIAL_OPS...` | Quasi: `Previous_OpenClaw\\...\\PROMPTFLOW_SPECIAL...` | 22,423 B | 779 | Reference | Generative promptflow for folder-local KB updates |')
w('| `02_RESEARCH_AND_DESIGN/CODEX_APPLY_PLAN...` | Quasi: `Previous_OpenClaw\\...\\CODEX_APPLY_PLAN...` | 14,780 B | 367 | Reference | Apply plan for hygiene patchset automation |')
w('| `02_RESEARCH_AND_DESIGN/APPENDIX_KB_SOURCE_MANIFEST.md` | Quasi: `Previous_OpenClaw\\...\\APPENDIX_KB_SOURCE...` | 12,108 B | 141 | Reference | Source coverage, duplication, role fit, authority risk |')
w('| `02_RESEARCH_AND_DESIGN/APPENDIX_KB_CANDIDATE_LEDGER.md` | Quasi: `Previous_OpenClaw\\...\\APPENDIX_KB_CANDIDATE...` | 10,944 B | 139 | Reference | Candidate rules scoring matrix and promotion ledger |')
w('| `02_RESEARCH_AND_DESIGN/APPENDIX_KB_QA_AND_NEXT_RESEARCH...` | Quasi: `Previous_OpenClaw\\...\\APPENDIX_KB_QA...` | 10,560 B | 142 | Reference | Non-blocking hygiene backlog and research roadmap |')
w('| `02_RESEARCH_AND_DESIGN/APPENDIX_KB_INFORMATION_RANKING...` | Quasi: `Previous_OpenClaw\\...\\APPENDIX_KB_INFO...` | 7,770 B | 46 | Reference | Ranked information units and scaffold routing |')
w('| `02_RESEARCH_AND_DESIGN/APPENDIX_KB_ANTI_DRIFT_EVIDENCE.md` | Quasi: `Previous_OpenClaw\\...\\APPENDIX_KB_ANTI...` | 7,456 B | 86 | Reference | Empirical failure evidence and anti-drift safeguards |')
w('| `02_RESEARCH_AND_DESIGN/ChangesHygiene.md` | Quasi: `Previous_OpenClaw\\...\\ChangesHygiene.md` | 17,654 B | 196 | Reference | Historical modification ledger for v2 hygiene overhaul |')
w('| `02_RESEARCH_AND_DESIGN/PROMPTFLOW_HYGIENE_CLEAN...` | Quasi: `Previous_OpenClaw\\...\\PROMPTFLOW_HYGIENE...` | 8,305 B | 161 | Reference | Unified diff manufacturing promptflow & validation |')
w('| `02_RESEARCH_AND_DESIGN/PATCHSET_VALIDATION_REPORT.md` | Quasi: `Previous_OpenClaw\\...\\PATCHSET_VALIDATION...` | 6,739 B | 127 | Reference | Patchset testing and validation evidence report |')
w('| `02_RESEARCH_AND_DESIGN/LEARNING_QUEUE.md` | Quasi: `Previous_OpenClaw\\...\\LEARNING_QUEUE.md` | 5,033 B | 100 | Reference | Populated candidate promotion queue |')
w('| `02_RESEARCH_AND_DESIGN/special_ops__hygiene_clean.md` | Quasi: `Previous_OpenClaw\\...\\special_ops...md` | 2,610 B | 111 | Reference | Historical OpenClaw agent card definition |')
w('| `90_SUPERSEDED/BEST_PRACTICES_empty.md` | Quasi: `OpenClaw_Setup\\...\\BEST_PRACTICES.md` | 561 B | 31 | Quarantined | Quarantined scaffold stub (EMPTY_STATE) |')
w('| `90_SUPERSEDED/MISTAKES_empty.md` | Quasi: `OpenClaw_Setup\\...\\MISTAKES.md` | 596 B | 32 | Quarantined | Quarantined scaffold stub (EMPTY_STATE) |')
w('| `90_SUPERSEDED/TEMPLATES_empty.md` | Quasi: `OpenClaw_Setup\\...\\TEMPLATES.md` | 547 B | 31 | Quarantined | Quarantined scaffold stub (EMPTY_STATE) |')
w('| `90_SUPERSEDED/LEARNING_QUEUE_empty.md` | Quasi: `OpenClaw_Setup\\...\\LEARNING_QUEUE.md` | 1,051 B | 45 | Quarantined | Quarantined empty queue schema placeholder |')
w('| `90_SUPERSEDED/legacy-hygiene-clean-TEMPLATES.md` | GitDev: `apex-meta\\...\\legacy-hygiene-clean-TEMPLATES.md` | 7,370 B | 243 | Historical | Earlier GitDev bridge template |')
w('| `90_SUPERSEDED/legacy-hygiene-clean-ESSENCE.md` | GitDev: `apex-meta\\...\\legacy-hygiene-clean-ESSENCE.md` | 7,241 B | 143 | Historical | Earlier GitDev bridge essence |')
w()
w('### 8.2 Directory Tree Architecture')
w('```')
w('C:\\Quasi Desktop\\AI_PreperationUntil_06-26\\LostAgents\\HygieneClean\\')
w('├── 00_INDEX/                                         [Governance & Navigation]')
w('│   └── INDEX.md                                      (Authoritative navigation manifest)')
w('│')
w('├── 01_CURRENT_HYGIENE_CLEAN/                         [Active Operational Core]')
w('│   ├── hygiene-clean-doctrine.md                     (Active weekly-orchestrator contract)')
w('│   ├── CORE.md                                       (Distilled operational core & invariants)')
w('│   ├── ESSENCE.md                                    (Canonical compact boundary doctrine)')
w('│   ├── BEST_PRACTICES.md                             (Populated best practices BP-HC-001..008)')
w('│   ├── MISTAKES.md                                   (Populated failure modes & Recovery Playbook)')
w('│   ├── TEMPLATES.md                                  (12 operational templates & closure checklist)')
w('│   └── HYGIENE_CLEAN_UNIFIED_DOCTRINE.md             (Consolidated production specification)')
w('│')
w('├── 02_RESEARCH_AND_DESIGN/                           [Deep Lore & Blueprints]')
w('│   ├── QA_HYGIENE_PROTOCOL.md                         (Crown Jewel: 15.1 KB, 424 L constitutional law)')
w('│   ├── Q&A&HygieneFuture.md                          (19.2 KB, 490 L deep research on hygiene dilemmas)')
w('│   ├── PROMPTFLOW_SPECIAL_OPS_HYGIENE_CLEAN_KB...   (22.4 KB, 779 L generative recipe)')
w('│   ├── CODEX_APPLY_PLAN_HYGIENE_CLEAN_PATCHSET.md    (14.8 KB, 367 L automated patchset runbook)')
w('│   ├── APPENDIX_KB_SOURCE_MANIFEST.md                (12.1 KB, 141 L source coverage & duplicate ledger)')
w('│   ├── APPENDIX_KB_CANDIDATE_LEDGER.md               (10.9 KB, 139 L candidate scoring matrix)')
w('│   ├── APPENDIX_KB_QA_AND_NEXT_RESEARCH_PLAN.md      (10.6 KB, 142 L backlog & deferred roadmap)')
w('│   ├── APPENDIX_KB_INFORMATION_RANKING_LEDGER.md     (7.8 KB, 46 L information ranking ledger)')
w('│   ├── APPENDIX_KB_ANTI_DRIFT_EVIDENCE.md            (7.5 KB, 86 L anti-drift postmortem evidence)')
w('│   ├── ChangesHygiene.md                             (17.7 KB, 196 L historical modification trace)')
w('│   ├── PROMPTFLOW_HYGIENE_CLEAN_UNIFIED_DIFF...      (8.3 KB, 161 L diff manufacturing promptflow)')
w('│   ├── PATCHSET_VALIDATION_REPORT.md                 (6.7 KB, 127 L patchset validation proof)')
w('│   ├── LEARNING_QUEUE.md                             (5.0 KB, 100 L populated candidate queue)')
w('│   └── special_ops__hygiene_clean.md                 (2.6 KB, 111 L historical agent definition)')
w('│')
w('└── 90_SUPERSEDED/                                    [Quarantined Scaffolds & Historical]')
w('    ├── BEST_PRACTICES_empty.md                       (561 B — Quarantined EMPTY_STATE stub)')
w('    ├── MISTAKES_empty.md                             (596 B — Quarantined EMPTY_STATE stub)')
w('    ├── TEMPLATES_empty.md                            (547 B — Quarantined EMPTY_STATE stub)')
w('    ├── LEARNING_QUEUE_empty.md                       (1,051 B — Quarantined empty queue stub)')
w('    ├── legacy-hygiene-clean-TEMPLATES.md             (7,370 B — Historical GitDev bridge template)')
w('    └── legacy-hygiene-clean-ESSENCE.md               (7,241 B — Historical GitDev bridge essence)')
w('```')
w()
w('---')
w()
w('## 9. Modern Architecture Alignment & WSL2 Integration Roadmap')
w()
w('### 9.1 Single-Engine WSL2 Storage Topology Alignment')
w('Per `AGENTS.md`, ADR-002, and `05-program-closeout/PLAN.md`:')
w('- **WSL2 Native ext4 Execution:** All Linux agent tools (`apex-sync`, `cross-linker`, python test harnesses) run strictly within native ext4 paths (`/root/workspaces/<repo>`), completely avoiding `/mnt/c` Windows 9P mounts. 9P filesystem latency causes severe I/O lag, false file-locking contention, and unkillable kernel D-state locks during multi-file lint sweeps.')
w('- **Shared Engine Reality:** Single WSL2-native Docker daemon with shared PostgreSQL; Docker Desktop is retired.')
w('- **File-Backed Persistence:** Hygiene Clean enforces the absolute invariant that lint sweep results and closure states are written directly to disk (`run-record.schema.md`, `handoff-packet.schema.md`). An interrupted run is 100% resumable from disk alone.')
w()
w('### 9.2 Plan-Sync-Session Backbone & Deterministic Sweeps Integration')
w('Hygiene Clean check families integrate directly into the three-tier Python backbone:')
w('1. **`apex-plan` (Planning Phase):** Hygiene Clean audits task definitions before acceptance, checking for broken prerequisites, unmapped paths, or missing project cards (Interface Check).')
w('2. **`apex-sync` (Scoring & Validation Phase):** `scripts/apex_sync.py` executes deterministic dependency and pointer checks. If broken references or stale timestamps are discovered, `apex-sync` raises a P1/P0 finding, blocking dry-run confirmation until remediated.')
w('3. **`apex-session` (Commit & Promotion Phase):** Prior to committing handoff packets to `apex-meta/handoff/`, Hygiene Clean verifies exact-preservation metrics and confirms that no undeclared files were modified in the commit.')
w()
w('### 9.3 Production Roadmap for Live Contract Enhancement')
w('To complete the integration of the rescued doctrine into daily developer operations:')
w('1. **Upgrade `.claude/agents/` Contracts:** Reference `LostAgents\\HygieneClean\\01_CURRENT_HYGIENE_CLEAN\\CORE.md` and `HYGIENE_CLEAN_UNIFIED_DOCTRINE.md` as canonical truth in all agent prompts.')
w('2. **Enforce Co-Equal Gating in CI:** Integrate `QA_HYGIENE_PROTOCOL.md` P0/P1 rules into pre-commit and pre-push hooks, rejecting commits that contain broken wikilinks, unreferenced images, or missing frontmatter.')
w('3. **Standardize `finding_record` Formatting:** Adopt the 8-field minimal finding schema across all lint skills (`wiki-lint`, `cross-linker`, `code-understand`), ensuring universal machine readability and traceability.')
w()

content = "\n".join(out)
with open(target_file, 'w', encoding='utf-8') as f:
    f.write(content)

print(f"Successfully generated {target_file} ({len(content)} bytes, {len(out)} lines)")
